# Project: week5-5
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = week5-5.o
LINKOBJ  = week5-5.o
LIBS     = -L"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/include" -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Users/gseye/OneDrive/Desktop/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = week5-5.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Users\gseye\OneDrive\Desktop\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

week5-5.o: week5-5.c
	$(CC) -c week5-5.c -o week5-5.o $(CFLAGS)
